openapi: 3.0.0
info:
  contact:
    name: karmy
  title: apiSpec
  version: '1.0'
  description: Сервер авторизации
servers:
  - url: 'http://localhost:3000'
paths:
  '/getTabRowsByCatId/{tabName}/{catId}':
    get:
      summary: 'Получает все поля из таблицы, соответствующие catId'
      tags:
        - device
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items: {}
      operationId: get-getTabRowsByCatId
      description: 'Получает все поля из таблицы, соответствующие связанному значению id категории.'
      parameters: []
    parameters:
      - schema:
          type: string
          enum:
            - status
            - brand
            - supplier
            - device
        name: tabName
        in: path
        required: true
        description: 'название таблицы, см. разрешенные таблицы в свойстве enum'
      - schema:
          type: integer
        name: catId
        in: path
        description: id категории
        required: true
  '/getTable/{tabName}':
    get:
      summary: Получает все поля из таблицы
      tags:
        - other
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items: {}
        '400':
          description: Нет такой таблицы
      operationId: get-getTable
      description: Получает все поля из запрошенной таблицы
    parameters:
      - schema:
          type: string
        name: tabName
        in: path
        required: true
  '/addRowInTab/{tabName}':
    post:
      summary: Добавление новой строки в таблицу
      operationId: post-addRowInTab
      responses:
        '200':
          description: OK
      description: Добавление новой строки в таблицу
      tags:
        - other
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema: {}
        description: ''
    parameters:
      - schema:
          type: string
        name: tabName
        in: path
        required: true
  '/updRowInTab/{tabName}/{id}':
    post:
      summary: Редактирование строки таблицы
      operationId: post-updRowInTab
      responses:
        '200':
          description: OK
      tags:
        - other
      description: Редактирование строки таблицы
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema: {}
    parameters:
      - schema:
          type: string
        name: tabName
        in: path
        required: true
      - schema:
          type: integer
        name: id
        in: path
        required: true
components:
  schemas: {}
  securitySchemes: {}
tags:
  - name: device
  - name: other
